version: "3.8"
services:
    nginx:
      build: ./nginx/
      container_name: nginx-container
      ports:
          - 8080:80
      links:
          - php
      volumes:
          - ../game/:/var/www/html/

    php:
      build: ./php/
      container_name: php-container
      expose:
          - 9000
      volumes:
          - ../game/:/var/www/html/

    mysql:    
        image: mysql:5.7  
        container_name: mysql-container  
        environment:  
          MYSQL_ROOT_PASSWORD: secret  
          MYSQL_DATABASE: mydb  
          MYSQL_USER: myuser  
          MYSQL_PASSWORD: password